export const LOAD_PAYMNT_LIST_REQUEST = "LOAD_PAYMNT_LIST_REQUEST";
export const LOAD_PAYMNT_LIST_SUCCESS = "LOAD_PAYMNT_LIST_SUCCESS";
export const LOAD_PAYMNT_LIST_FAILURE = "LOAD_PAYMNT_LIST_FAILURE";

export const SET_CURRPAGELIST_REQUEST = "SET_CURRPAGELIST_REQUEST";
export const SET_CURRPAGELIST_SUCCESS = "SET_CURRPAGELIST_SUCCESS";
export const SET_CURRPAGELIST_FAILURE = "SET_CURRPAGELIST_FAILURE";

export const GET_TOTALCNT_REQUEST = "SET_TOTALCNT_REQUEST";
export const GET_TOTALCNT_SUCCESS = "SET_TOTALCNT_SUCCESS";
export const GET_TOTALCNT_FAILURE = "SET_TOTALCNT_FAILURE";

export const GET_CONTENTCNT_PERPAGE_REQUEST = "GET_CONTENTCNT_PERPAGE_REQUEST";
export const GET_CONTENTCNT_PERPAGE_SUCCESS = "GET_CONTENTCNT_PERPAGE_SUCCESS";
export const GET_CONTENTCNT_PERPAGE_FAILURE = "GET_CONTENTCNT_PERPAGE_FAILURE";

export const SET_PAGENUM_REQUEST = "SET_PAGENUM_REQUEST";
export const SET_PAGENUM_SUCCESS = "SET_PAGENUM_SUCCESS";
export const SET_PAGENUM_FAILURE = "SET_PAGENUM_FAILURE";

export const SET_CONTENT_EDITABLE_REQUEST = "SET_CONTENT_EDITABLE_REQUEST";
export const SET_CONTENT_EDITABLE_SUCCESS = "SET_CONTENT_EDITABLE_SUCCESS";
export const SET_CONTENT_EDITABLE_FAILURE = "SET_CONTENT_EDITABLE_FAILURE";

export const SET_TEMPPAYMNTLIST_UPDATE_REQUEST = "SET_TEMPPAYMNTLIST_UPDATE_REQUEST";
export const SET_TEMPPAYMNTLIST_UPDATE_SUCCESS = "SET_TEMPPAYMNTLIST_UPDATE_SUCCESS";
export const SET_TEMPPAYMNTLIST_UPDATE_FAILURE = "SET_TEMPPAYMNTLIST_UPDATE_FAILURE";

export const SET_MULTIUPDATE_REQUEST = "SET_MULTIUPDATE_REQUEST";
export const SET_MULTIUPDATE_SUCCESS = "SET_MULTIUPDATE_SUCCESS";
export const SET_MULTIUPDATE_FAILURE = "SET_MULTIUPDATE_FAILURE";

export const SET_PAYMNTDATA_DELETE_REQUEST = "SET_PAYMNTDATA_DELETE_REQUEST";
export const SET_PAYMNTDATA_DELETE_SUCCESS = "SET_PAYMNTDATA_DELETE_SUCCESS";
export const SET_PAYMNTDATA_DELETE_FAILURE = "SET_PAYMNTDATA_DELETE_FAILURE";

export const SET_PAYMNTDATA_MULTIDELETE_REQUEST = "SET_PAYMNTDATA_MULTIDELETE_REQUEST";
export const SET_PAYMNTDATA_MULTIDELETE_SUCCESS = "SET_PAYMNTDATA_MULTIDELETE_SUCCESS";
export const SET_PAYMNTDATA_MULTIDELETE_FAILURE = "SET_PAYMNTDATA_MULTIDELETE_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOG_OUT_REQUEST = "LOG_OUT_REQUEST";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE";

export const LOG_INIT_REQUEST = "LOG_INIT_REQUEST";
export const LOG_INIT_SUCCESS = "LOG_INIT_SUCCESS";
export const LOG_INIT_FAILURE = "LOG_INIT_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const MESSAGE_CLEAR = "MESSAGE_CLEAR";

export const LOAD_PAYMNT_INFO_REQUEST = "LOAD_PAYMNT_INFO_REQUEST";
export const LOAD_PAYMNT_INFO_SUCCESS = "LOAD_PAYMNT_INFO_SUCCESS";
export const LOAD_PAYMNT_INFO_FAILURE = "LOAD_PAYMNT_INFO_FAILURE";

export const LOAD_PAYMNT_MAIN_SAVE_REQUEST = "LOAD_PAYMNT_MAIN_SAVE_REQUEST";
export const LOAD_PAYMNT_MAIN_SAVE_SUCCESS = "LOAD_PAYMNT_MAIN_SAVE_SUCCESS";
export const LOAD_PAYMNT_MAIN_SAVE_FAILURE = "LOAD_PAYMNT_MAIN_SAVE_FAILURE";

export const LOAD_PAYMNT_HIS_SAVE_REQUEST = "LOAD_PAYMNT_HIS_SAVE_REQUEST";
export const LOAD_PAYMNT_HIS_SAVE_SUCCESS = "LOAD_PAYMNT_HIS_SAVE_SUCCESS";
export const LOAD_PAYMNT_HIS_SAVE_FAILURE = "LOAD_PAYMNT_HIS_SAVE_FAILURE";

export const SET_COOKIE_REQUEST = "SET_COOKIE_REQUEST";
export const SET_COOKIE_SUCCESS = "SET_COOKIE_SUCCESS";
export const SET_COOKIE_FAILURE = "SET_COOKIE_FAILURE";

export const LOAD_SSR_PAYMNT_LIST_REQUEST = "LOAD_SSR_PAYMNT_LIST_REQUEST";
export const LOAD_SSR_PAYMNT_LIST_SUCCESS = "LOAD_SSR_PAYMNT_LIST_SUCCESS";
export const LOAD_SSR_PAYMNT_LIST_FAILURE = "LOAD_SSR_PAYMNT_LIST_FAILURE";

export const SET_SSR_USER_REQUEST = "SET_SSR_USER_REQUEST";
export const SET_SSR_USER_SUCCESS = "SET_SSR_USER_SUCCESS";
export const SET_SSR_USER_FAILURE = "SET_SSR_USER_FAILURE";

export const SET_SSR_USER2_REQUEST = "SET_SSR_USER2_REQUEST";
export const SET_SSR_USER2_SUCCESS = "SET_SSR_USER2_SUCCESS";
export const SET_SSR_USER2_FAILURE = "SET_SSR_USER2_FAILURE";

export const LOAD_COMP_INFO_REQUEST = "LOAD_COMP_INFO_REQUEST";
export const LOAD_COMP_INFO_SUCCESS = "LOAD_COMP_INFO_SUCCESS";
export const LOAD_COMP_INFO_FAILURE = "LOAD_COMP_INFO_FAILURE";


